import Head from 'next/head';

export default function Home() {
  return (
    <>
      <Head>
        <title>Magnus Fröbom Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <section className=" bg-blue-900 h-screen">
          <nav>
            
          </nav>
        </section>
      </main>
    </>
  );
}
